name: Test and Build Notebooks ES Plugin

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 1.14
        uses: actions/setup-java@v1
        with:
          java-version: 1.14

      - name: Build with Gradle
        run: |
          cd es-notebooks
          ./gradlew build

      - name: Create Artifact Path
        run: |
          mkdir -p es-notebooks-builds
          cp -r ./es-notebooks/build/distributions/*.zip es-notebooks-builds/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: es-notebooks
          path: es-notebooks-builds
